# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: ORMIR Data Sharing Guidelines
author: Open and Reproducible Musculoskeletal Imaging Research Community
#logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  
# References
bibtex_bibfiles:
    - references.bib
sphinx:
  config:
    bibtex_reference_style: author_year

# Specify the list of extensions to use
markdown_extensions:
  - myst_parser

# Configure the Myst extension
myst_enable_extensions:
  - colon_fence
  - deflist
  - tasklist
  - toc

# Information about where the book exists on the web
repository:
  url: https://github.com/ORMIRcommunity/ormir_index_guidelines  # Online location of your book
  #path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true


